language: ruby
rvm:
  - 2.7.2
branches:
  only:
  - develop
install:
  - gem install bundler:2.3.14
  - bundle install
  - nvm install 14.19.3
  - npm i -g yarn
  - bundle exec rails yarn:install
  - bundle exec rails webpacker:compile
services:
  - postgresql
before_script:
  - psql -c 'create database ur_better_house_test;' -U postgres
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.10.0
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: ur-better-house
    on:
      branch: develop
